language: java
jdk: oraclejdk8

# Define the services to use
services:
  - docker

before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db

# Run Unit Test and Integration Tests
script:
  - mvn verify
  - |
    mvn sonar:sonar \
    -Dsonar.projectKey=Vertrieb_sample-application-students \
    -Dsonar.organization=vertrieb-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=14a501ab408e7dd56f9b62266834fdcd528dd2be

# Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"

env:
  global:
    - secure: "pfMiuirwwR97ozR6ikTd/ViPNl3CJKD2xlTcg88Pkwzu0Qft0Tu23yYK/xa0pbEynkKJWMER241iIreyKmNX8HqRPZZ2a05ZzSEfiuL+P09UT4LxqSCeDOOKVAD2edpQp8hLmy1TkIWsIGcIbHB8skNOZscEwaVHqJ+H4zpDAv762YpNxyAH5l46fZhXND+ihWawnwPmrCox1CmsfDMBigmLvwJEUiwJmuN3OtAE56bx9M9GIckJAC3SA9pUn6+9ZpxvZ4JzmCPYxz/bhg96/+rvAqMypJAfRdP65+ol7i4T+zc0oQ3YGqESurcsUm4jnH+VbZqWbUnUClNq9vkdXnBdvwpo0i+ZDUYhIqFp7Ow04GdbO0m9p55JRnzYYmnZ7hxAu9F1ny6SgQyc9BxtrOPlb9M519NH0phAEnqjKju7JdPStUM4NLV88E3FUvwlSSSasJ/bL5wx6kHh2E1sFmCsvxvaNoK2pUNPdy44yFN3tKpvM62OEcSj5oTaVCfwKJNoDyALA7pLdUrflPsr+Omvm+AGcKzmUuUp5DFNZnR2XNRG01CT+2tTiGTBw2ty6Rx4j4ZXe1+H/l6wx0CyDSPbfUIzTVHqy9Cj6sBz6+tfJTVQj7/hnQuL92xPW8bhDODLmC9mVHvQLlVLxtsaOhjA0HKoZ8SQSsR21BqjVBM="
